# Nudging round 2

Concept: DEAP unlikely to have found precisely the best solutions, so take its answers and nudge the coefficients a bit to see if there's an even better answer nearby.

First show that this can result in a better fit (using the "fitness" metric) by manually picking out some coefficients that look better.

Show that we can't possibly try every single combination of nudging the coefficients (5^25 = 3x10^17, three hundred quadrillion or three hundred million billion possible combinations. The universe is around 4.4 hundred quadrillion seconds old, the Sun is around 1.5 hundred quadrillion seconds old) So try two combinations a second since the Sun formed and we'd only just have finished. 

But can manage 5 coeffs at a time (5^5 = 3125 combinations).

For each deprivation quantile separately, find the nudged coefficients that give the best fit in that quantile. But see that combining five good fits gives very poor fits to the total numbers of admissions from each age band.

Try the same for the age bands, but a similar result: can fit well to age but the combined good fits are bad fits to each deprivation quantile.

So have to consider all 25 coefficients together. No way to simplify the problem to 5 coeffs only.
Also expect that most of these three hundred quadrillion combinations would be rubbish. So find a way to try considerably fewer combinations, pick out only those that are likely to be any good.

Assume that the starting values are pretty good fits to the data and so that increasing or decreasing the value of only one coefficient is bound to make the fitness worse. Instead, force two changes at once: one coefficient must increase and another must decrease, and the two must be either in the same row (same deprivation level) or in the same column (same age band). Then pick the pair of changes that results in the best overall fitness. Continue to change either a pair or just one coefficient at once until no further improvements can be made. So in each pass, try a number of combinations, but not all three hundred quadrillion options, just the ones that are quite close to the starting values.

Try this walking nudge method on each of the 100 outputs from the genetic algorithm, and so find the best set of coefficients that is near to those starting points.

Results: 7 of the 100 sets converge on one set of values that have better fitness than the other 93 sets manage. Go with these as the "best" values.

In [1]:
import polars as pl
import os
import numpy as np
import itertools

## Load data

### Admissions

In [2]:
path_to_msoa_stats = os.path.join('data', 'msoa_cleaned.csv')

df_stats = pl.read_csv(path_to_msoa_stats)

In [3]:
df_stats.head()

shape: (5, 25)
┌──────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ MSOA     ┆ admissions ┆ IMD2019Sc ┆ All       ┆ … ┆ age_75   ┆ age_over8 ┆ depriv_qu ┆ depriv_qu │
│ ---      ┆ ---        ┆ ore       ┆ persons   ┆   ┆ ---      ┆ 0         ┆ antile_mi ┆ antile_ma │
│ str      ┆ f64        ┆ ---       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ n         ┆ x         │
│          ┆            ┆ f64       ┆ i64       ┆   ┆          ┆ f64       ┆ ---       ┆ ---       │
│          ┆            ┆           ┆           ┆   ┆          ┆           ┆ f64       ┆ f64       │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ Adur 001 ┆ 14.333333  ┆ 16.924833 ┆ 8815      ┆ … ┆ 371.993  ┆ 546.53    ┆ 0.4       ┆ 0.6       │
│ Adur 002 ┆ 7.333333   ┆ 6.4704    ┆ 7263      ┆ … ┆ 357.3396 ┆ 502.5996  ┆ 0.8       ┆ 1.0       │
│ Adur 003 ┆ 9.333333   ┆ 13.7334   ┆ 7354      ┆ … ┆ 309.6034 ┆ 486.0994  ┆ 0.6       ┆ 0.8       │
│ Adur 004 ┆ 21.0       ┆ 26.199857 ┆ 10582     ┆ … ┆ 388.3594 ┆ 675.1316  ┆ 0.2       ┆ 0.4       │
│ Adur 005 ┆ 13.666667  ┆ 11.7948   ┆ 9059      ┆ … ┆ 385.0075 ┆ 599.7058  ┆ 0.6       ┆ 0.8       │
└──────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

Pick out column names for the health and age proportions:

In [70]:
props_age = [
    'age_less65_proportion', 'age_65_proportion', 'age_70_proportion',
    'age_75_proportion', 'age_over80_proportion'
]
age_numbers = [p.replace('_proportion', '') for p in props_age]
qmin_list = sorted(df_stats['depriv_quantile_min'].unique())

# Names of coeffs:
coeff_names = [f'{a}_q{str(round(q, 1)).replace(".", "")}'
               for q in qmin_list for a in age_numbers]
# Check the first few:
print(coeff_names[:3])

# Quantile names:
quantile_str_list = sorted(list(set([c.split('_')[-1] for c in coeff_names])))

['age_less65_q00', 'age_65_q00', 'age_70_q00']

Gather admissions data by deprivation quantile:

In [5]:
admissions_lists = []
x_lists = []

for qmin in qmin_list:
    df_stats_here = df_stats.filter(df_stats['depriv_quantile_min'] == qmin)
    # MSOA data in the same order as those coefficients:
    x_lists_here = [df_stats_here[a] for a in age_numbers]
    admissions_here = df_stats_here['admissions'].to_numpy().tolist()
    # Store:
    admissions_lists.append(admissions_here)
    x_lists.append(x_lists_here)

### Age-admissions coefficients

Starting SSNAP coefficients:

In [6]:
df_pop_admissions = pl.read_csv(os.path.join('outputs', 'ssnap_coeffs.csv'))

In [7]:
df_pop_admissions

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────┬────────────┬────────────┬────────────┬────────────┐
│ Age Groups ┆ population ┆ prop_of_al ┆ count ┆ prop_of_al ┆ admissions ┆ admissions ┆ prob_strok │
│ ---        ┆ ---        ┆ l_pop      ┆ ---   ┆ l_admissio ┆ _annual    ┆ _annual_bo ┆ e_given_ag │
│ str        ┆ i64        ┆ ---        ┆ i64   ┆ ns         ┆ ---        ┆ ost        ┆ e          │
│            ┆            ┆ f64        ┆       ┆ ---        ┆ f64        ┆ ---        ┆ ---        │
│            ┆            ┆            ┆       ┆ f64        ┆            ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════════╪═══════╪════════════╪════════════╪════════════╪════════════╡
│ Under 65   ┆ 45933245   ┆ 0.816055   ┆ 38827 ┆ 0.231449   ┆ 12942.3333 ┆ 18737.6681 ┆ 0.000408   │
│            ┆            ┆            ┆       ┆            ┆ 3          ┆ 9          ┆            │
│ 65-69      ┆ 2796740    ┆ 0.049687   ┆ 15324 ┆ 0.091347   ┆ 5108.0     ┆ 7395.26689 ┆ 0.002644   │
│ 70-74      ┆ 2779326    ┆ 0.049378   ┆ 21508 ┆ 0.12821    ┆ 7169.33333 ┆ 10379.6267 ┆ 0.003735   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 4          ┆            │
│ 75-79      ┆ 1940686    ┆ 0.034478   ┆ 24150 ┆ 0.143959   ┆ 8050.0     ┆ 11654.6394 ┆ 0.006005   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 8          ┆            │
│ 80 and     ┆ 2836964    ┆ 0.050402   ┆ 67947 ┆ 0.405035   ┆ 22649.0    ┆ 32790.7987 ┆ 0.011558   │
│ over       ┆            ┆            ┆       ┆            ┆            ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴────────────┴────────────┴────────────┴────────────┘

Pick out SSNAP coefficients:

In [8]:
coeffs_ssnap = df_pop_admissions['prob_stroke_given_age'].to_numpy()

coeffs_ssnap

array([0.000408, 0.002644, 0.003735, 0.006005, 0.011558])

Turn them into a dictionary:

In [9]:
labels = ['less65', '65', '70', '75', 'over80']
coeffs_ssnap_dict = (
    dict(zip(labels, df_pop_admissions['prob_stroke_given_age'].to_numpy())))

coeffs_ssnap_dict

{'less65': 0.000408,
 '65': 0.002644,
 '70': 0.003735,
 '75': 0.006005,
 'over80': 0.011558}

Pick out admissions numbers:

In [10]:
admissions_by_age = (
    df_pop_admissions['admissions_annual_boost'].to_numpy().flatten())

### Best results from genetic algorithm

Data stored as scale factors for the SSNAP-derived coefficients.

In [11]:
df_best_gens = pl.read_csv(os.path.join('outputs', 'best_inds_deap.csv'))

In [12]:
df_best_gens.head()

shape: (5, 34)
┌──────────────┬───────┬──────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ dir          ┆ # gen ┆ age_less65_q ┆ age_65_q00 ┆ … ┆ r2_q02   ┆ r2_q04   ┆ r2_q06   ┆ r2_q08   │
│ ---          ┆ ---   ┆ 00           ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ f64   ┆ ---          ┆ f64        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
│              ┆       ┆ f64          ┆            ┆   ┆          ┆          ┆          ┆          │
╞══════════════╪═══════╪══════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ randomseed00 ┆ 33.0  ┆ 1.3          ┆ 1.2        ┆ … ┆ 0.579147 ┆ 0.616005 ┆ 0.598245 ┆ 0.606993 │
│ randomseed01 ┆ 33.0  ┆ 1.1          ┆ 1.3        ┆ … ┆ 0.579147 ┆ 0.616005 ┆ 0.583824 ┆ 0.606993 │
│ randomseed02 ┆ 43.0  ┆ 1.273        ┆ 1.308      ┆ … ┆ 0.583466 ┆ 0.616005 ┆ 0.606683 ┆ 0.606993 │
│ randomseed03 ┆ 28.0  ┆ 1.171        ┆ 1.3        ┆ … ┆ 0.583466 ┆ 0.631482 ┆ 0.605116 ┆ 0.580367 │
│ randomseed04 ┆ 39.0  ┆ 1.2          ┆ 1.2        ┆ … ┆ 0.579147 ┆ 0.631482 ┆ 0.612783 ┆ 0.606993 │
└──────────────┴───────┴──────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

Convert the scale factors to the actual age-deprivation coefficient values using the SSNAP coefficients.

In [13]:
for coeff in coeff_names:
    key = coeff.split('_')[1]
    new_data = df_best_gens[coeff] * coeffs_ssnap_dict[key]
    
    df_best_gens = df_best_gens.with_columns(pl.Series(coeff, new_data))

Round results:

In [14]:
# Set up dictionary with how many decimal places to round to:
labels = ['less65', '65', '70', '75', 'over80']
round_dict = dict(zip(labels, [4, 3, 3, 3, 3]))

for coeff in coeff_names:
    key = coeff.split('_')[1]
    new_data = np.round(df_best_gens[coeff], round_dict[key])
    
    df_best_gens = df_best_gens.with_columns(pl.Series(coeff, new_data))

Drop the measures of goodness of fit now that the coefficients have been rounded:

In [15]:
df_best_gens = df_best_gens.drop(
    ['fitness'] + [c for c in df_best_gens.columns if c.startswith('r2')])

## Recalculate fitness

In [16]:
def predict_admissions(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    # yhat = (x_lists * coeffs.reshape(len(coeffs), 1)).sum(axis=0)
    yhat = sum(
        [x_lists[i] * coeffs[i] for i in range(len(coeffs))]
    )
    return yhat.to_numpy().tolist()

In [17]:
def predict_admissions_each_age(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    yhat = (
        [(x_lists[i] * coeffs[i]).sum() for i in range(len(coeffs))]
    )
    return yhat

Goodness check option 1: This calculates the sum of the square of the differences between predicted and actual admission numbers:

In [18]:
def find_square_residuals(yhat, y):
    # Difference from actual:
    sqres = (np.array(yhat) - np.array(y))**2.0
    # Sum of differences:
    sum_sqres = sqres.sum()
    return np.sqrt(sum_sqres)

In [101]:
def many_sum_sqres(individual, x_lists, admissions_lists):
    # Predictions for each MSOA:
    predictions_lists = []
    sum_sqres_by_depriv = []
    for i in range(5):
        coeffs = individual[(i*5):(i*5)+5]  # coeffs for this depriv.
        yhat = predict_admissions(x_lists[i], coeffs)
        sum_sqres = find_square_residuals(yhat, admissions_lists[i])
        predictions_lists.append(yhat)
        sum_sqres_by_depriv.append(sum_sqres)


    # Combine lists:
    observed_all = sum(admissions_lists, [])
    predicted_all = sum(predictions_lists, [])
    # Calculate sum of square residuals across all MSOA:
    sum_sqres = find_square_residuals(predicted_all, observed_all)

    return sum_sqres, sum_sqres_by_depriv

In [102]:
# the goal ('fitness') function to be maximized
def eval_admissions(individual, admissions_lists, x_lists, admissions_by_age):

    # Predictions for each age band across England:
    predictions_by_age = [0.0] * 5
    for i in range(5):
        # Population numbers for areas in this quantile:
        x_lists_here = x_lists[i]
        # Separate prediction for each deprivation quantile:
        coeffs = individual[(i*5):(i*5)+5] #* np.array(coeffs_ssnap)
        yhat_list = predict_admissions_each_age(x_lists_here, coeffs)
        # predictions_lists.append(yhat)
        for j, y in enumerate(yhat_list):
            predictions_by_age[j] += y
    # Divide the admissions by age band by the observed values:
    for j in range(len(predictions_by_age)):
        predictions_by_age[j] /= admissions_by_age[j]
    # Wrongness ratio factor:
    rat = sum(np.abs(np.array(predictions_by_age) - 1.0)) + 1.0

    sum_sqres, sum_sqres_by_depriv = many_sum_sqres(individual, x_lists, admissions_lists)
    
    return (sum_sqres, rat, sum_sqres * rat, predictions_by_age, sum_sqres_by_depriv)

Recalculate fitnesses for the genetic algorithm outputs:

In [20]:
def eval_fitness_to_df(df_best_gens, admissions_lists, x_lists, admissions_by_age, coeff_names, concat=False):
    eval_dict = {}
    eval_labels = [
        'sum_sqres',
        'wrong_rat',
        'fitness',
        'wrong_rat_under65',
        'wrong_rat_65',
        'wrong_rat_70',
        'wrong_rat_75',
        'wrong_rat_over80',
        'sum_sqres_q00',
        'sum_sqres_q02',
        'sum_sqres_q04',
        'sum_sqres_q06',
        'sum_sqres_q08',
    ]
    eval_dict = dict(zip(eval_labels, [[] for e in eval_labels]))
    
    for d in range(len(df_best_gens)):
        df = df_best_gens[d]
        # Pick out coefficients:
        coeffs = df[coeff_names].to_numpy().flatten()
        sum_sqres, rat, fitness, ratios_by_age, sum_sqres_by_depriv = eval_admissions(
            coeffs,
            admissions_lists,
            x_lists,
            admissions_by_age
        )
        eval_dict['sum_sqres'].append(sum_sqres)
        eval_dict['wrong_rat'].append(rat)
        eval_dict['fitness'].append(fitness)
        eval_dict['wrong_rat_under65'].append(ratios_by_age[0])
        eval_dict['wrong_rat_65'].append(ratios_by_age[1])
        eval_dict['wrong_rat_70'].append(ratios_by_age[2])
        eval_dict['wrong_rat_75'].append(ratios_by_age[3])
        eval_dict['wrong_rat_over80'].append(ratios_by_age[4])
        eval_dict['sum_sqres_q00'].append(sum_sqres_by_depriv[0])
        eval_dict['sum_sqres_q02'].append(sum_sqres_by_depriv[1])
        eval_dict['sum_sqres_q04'].append(sum_sqres_by_depriv[2])
        eval_dict['sum_sqres_q06'].append(sum_sqres_by_depriv[3])
        eval_dict['sum_sqres_q08'].append(sum_sqres_by_depriv[4])

    # Either start a new blank dataframe or add the fitnesses to the
    # input df:
    df_new = df_best_gens if concat else pl.DataFrame()
    for key, v in eval_dict.items():
        df_new = df_new.with_columns(pl.Series(key, v))
    return df_new

In [21]:
df_best_gens = eval_fitness_to_df(df_best_gens, admissions_lists, x_lists, admissions_by_age, coeff_names, concat=True)

View results:

In [22]:
df_best_gens.sort('fitness').head()

shape: (5, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 22.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 74         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 10         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 94         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
│ randomseed ┆ 20.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 107.72117 ┆ 102.23269 │
│ 26         ┆       ┆            ┆            ┆   ┆ 3         ┆ 1         ┆ 7         ┆ 6         │
│ randomseed ┆ 56.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 57         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

Pick out the best coeffs so far:

In [78]:
df_coeffs_best_deap = df_best_gens.sort('fitness')[0]
coeffs_best_deap = df_coeffs_best_deap[coeff_names].to_numpy().flatten()

## Tests

### Test 1: manual tweaking of coefficients

can other combos be better?

From the table above we can see that the best overall combo is not made up of the best combo for each deprivation quantile:

In [30]:
sum_sqres_cols = [c for c in df_best_gens.columns if c.startswith('sum_sqres')]

d1 = df_best_gens.sort('sum_sqres')[0][sum_sqres_cols]
d2 = df_best_gens[sum_sqres_cols].min()

d1 = d1.with_columns(pl.Series('coeff_combo', ['max_sum_sqres_overall']))
d2 = d2.with_columns(pl.Series('coeff_combo', [f'max_sum_sqres_each_depriv']))

display(pl.concat((d1, d2)))

shape: (2, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ sum_sqres  ┆ sum_sqres_q0 ┆ sum_sqres_q0 ┆ sum_sqres_q ┆ sum_sqres_q ┆ sum_sqres_q ┆ coeff_combo │
│ ---        ┆ 0            ┆ 2            ┆ 04          ┆ 06          ┆ 08          ┆ ---         │
│ f64        ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ str         │
│            ┆ f64          ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆             │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 237.454911 ┆ 110.501962   ┆ 107.849722   ┆ 106.276266  ┆ 103.905822  ┆ 102.232696  ┆ max_sum_sqr │
│            ┆              ┆              ┆             ┆             ┆             ┆ es_overall  │
│ 237.454911 ┆ 110.501962   ┆ 107.800573   ┆ 106.276266  ┆ 103.472366  ┆ 99.88842    ┆ max_sum_sqr │
│            ┆              ┆              ┆             ┆             ┆             ┆ es_each_dep │
│            ┆              ┆              ┆             ┆             ┆             ┆ riv         │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

The second row of the table has the best r-squared for each deprivation quantile. Its values are higher for the second and the two most-deprived quantiles than in the overall best combo.

View the best combo for these deprivation quantiles:

In [31]:
for q in ['q02', 'q06', 'q08']:
    coeffs_q = [c for c in df_best_gens.columns if q in c]
    mask = df_best_gens.sort('sum_sqres')[f'sum_sqres_{q}'] == df_best_gens[f'sum_sqres_{q}'].min()

    d1 = df_best_gens.sort('sum_sqres')[0][coeffs_q]
    d2 = df_best_gens.sort('sum_sqres').filter(mask)[0][coeffs_q]
    d1 = d1.with_columns(pl.Series('coeff_combo', ['best_overall']))
    d2 = d2.with_columns(pl.Series('coeff_combo', [f'best_{q}']))

    display(pl.concat((d1, d2)))

shape: (2, 7)
┌──────────────┬────────────┬────────────┬────────────┬──────────────┬──────────────┬──────────────┐
│ age_less65_q ┆ age_65_q02 ┆ age_70_q02 ┆ age_75_q02 ┆ age_over80_q ┆ sum_sqres_q0 ┆ coeff_combo  │
│ 02           ┆ ---        ┆ ---        ┆ ---        ┆ 02           ┆ 2            ┆ ---          │
│ ---          ┆ f64        ┆ f64        ┆ f64        ┆ ---          ┆ ---          ┆ str          │
│ f64          ┆            ┆            ┆            ┆ f64          ┆ f64          ┆              │
╞══════════════╪════════════╪════════════╪════════════╪══════════════╪══════════════╪══════════════╡
│ 0.0004       ┆ 0.003      ┆ 0.004      ┆ 0.007      ┆ 0.013        ┆ 107.849722   ┆ best_overall │
│ 0.0004       ┆ 0.003      ┆ 0.004      ┆ 0.006      ┆ 0.014        ┆ 107.800573   ┆ best_q02     │
└──────────────┴────────────┴────────────┴────────────┴──────────────┴──────────────┴──────────────┘

shape: (2, 7)
┌──────────────┬────────────┬────────────┬────────────┬──────────────┬──────────────┬──────────────┐
│ age_less65_q ┆ age_65_q06 ┆ age_70_q06 ┆ age_75_q06 ┆ age_over80_q ┆ sum_sqres_q0 ┆ coeff_combo  │
│ 06           ┆ ---        ┆ ---        ┆ ---        ┆ 06           ┆ 6            ┆ ---          │
│ ---          ┆ f64        ┆ f64        ┆ f64        ┆ ---          ┆ ---          ┆ str          │
│ f64          ┆            ┆            ┆            ┆ f64          ┆ f64          ┆              │
╞══════════════╪════════════╪════════════╪════════════╪══════════════╪══════════════╪══════════════╡
│ 0.0004       ┆ 0.002      ┆ 0.003      ┆ 0.005      ┆ 0.011        ┆ 103.905822   ┆ best_overall │
│ 0.0004       ┆ 0.002      ┆ 0.003      ┆ 0.006      ┆ 0.011        ┆ 103.472366   ┆ best_q06     │
└──────────────┴────────────┴────────────┴────────────┴──────────────┴──────────────┴──────────────┘

shape: (2, 7)
┌──────────────┬────────────┬────────────┬────────────┬──────────────┬──────────────┬──────────────┐
│ age_less65_q ┆ age_65_q08 ┆ age_70_q08 ┆ age_75_q08 ┆ age_over80_q ┆ sum_sqres_q0 ┆ coeff_combo  │
│ 08           ┆ ---        ┆ ---        ┆ ---        ┆ 08           ┆ 8            ┆ ---          │
│ ---          ┆ f64        ┆ f64        ┆ f64        ┆ ---          ┆ ---          ┆ str          │
│ f64          ┆            ┆            ┆            ┆ f64          ┆ f64          ┆              │
╞══════════════╪════════════╪════════════╪════════════╪══════════════╪══════════════╪══════════════╡
│ 0.0003       ┆ 0.002      ┆ 0.003      ┆ 0.005      ┆ 0.01         ┆ 102.232696   ┆ best_overall │
│ 0.0003       ┆ 0.002      ┆ 0.003      ┆ 0.005      ┆ 0.011        ┆ 99.88842     ┆ best_q08     │
└──────────────┴────────────┴────────────┴────────────┴──────────────┴──────────────┴──────────────┘

Manually adjust the values in the best combo to recreate the best r-squared for each deprivation quantile.

In [32]:
# Pick out coeffs:
coeffs = df_best_gens.filter(df_best_gens['sum_sqres'] == df_best_gens['sum_sqres'].min())[coeff_names].to_numpy().flatten()
# Update some:
coeffs[coeff_names.index('age_75_q02')] = 0.006
coeffs[coeff_names.index('age_over80_q02')] = 0.014
coeffs[coeff_names.index('age_75_q06')] = 0.006
coeffs[coeff_names.index('age_over80_q08')] = 0.011

Check that coeffs still increase with age (across) and deprivation level (upwards):

In [33]:
coeffs.reshape(5, 5)

array([[0.0005, 0.004 , 0.005 , 0.007 , 0.014 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.014 ],
       [0.0004, 0.002 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.003 , 0.006 , 0.011 ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.011 ]])

What's the effect on overall R^2?

In [35]:
sum_sqres, rat, fitness, ratios_by_age, sum_sqres_by_depriv = eval_admissions(
    coeffs,
    admissions_lists,
    x_lists,
    admissions_by_age
)

# Best R^2 from all genetic algorithm results:
fitness_best = df_best_gens['fitness'].min()
sum_sqres_best = df_best_gens['sum_sqres'].min()

print(f'New sum_sqres: {sum_sqres:.4f}')
print(f'Old sum_sqres: {sum_sqres_best:.4f}')

print(f'New fitness: {fitness:.4f}')
print(f'Old fitness: {fitness_best:.4f}')

New sum_sqres: 236.2425
Old sum_sqres: 237.4549
New fitness: 271.9798
Old fitness: 252.5461

The overall sum of square residuals has decreased with this manual changing of the coefficients - good - but the overall fitness taking into account numbers of admissions in each age band has increased - bad.

It is worth trying more combinations of coefficients near the found values to check whether any small adjustments can make better results. The genetic algorithm isn't likely to have tried every good combination by chance, and there could be other better options yet to be discovered.

### Test 2: Random offsets

Are there any combos of coefficients where the fitness is better than the current best?

Can't try every combination, so here pick some out at random and see if any are better by chance.

Allow these offsets for the coeffs:

In [36]:
offsets = np.array([1e-4, 1e-3, 1e-3, 1e-3, 1e-3] * 5)

What probability of no change do we need to have an average of 3 coeffs changing?

In [37]:
((25.0 - 3.0)/25.0)

0.88

Generate 10,000 lists of changes to the starting parameters. Each change may be either zero, or plus or minus one or two steps from the start value. Each coefficient has an 88% chance of not changing, a 4% chance of moving up or down one step, and a 2% chance of moving up or down two steps.

In [38]:
seeds_list = []
random_offsets = []
for seed in np.arange(10000):
    np.random.seed(seed)
    r = list(offsets * np.random.choice(np.arange(-2, 3, 1), 25, p=[0.02, 0.04, 0.88, 0.04, 0.02]))
    if r not in random_offsets:
        random_offsets.append(r)
        seeds_list.append(seed)

Check how many sets of changes were kept after removing repeats:

In [39]:
len(random_offsets)

7730

For each set in turn, apply the changes to the set of starting parameters (here the best one of the 100 sets of outputs from the genetic algorithm). Check that the resulting coefficients obey the rules: they must increase with age band and with deprivation level. If this check is passed, then keep a copy of the resulting coefficients.

In [40]:
coeffs = coeffs_best_deap
results = [list(coeffs)]
seeds_used = [-42]

for s, seed in enumerate(seeds_list):
    r = coeffs + random_offsets[s]
    # Check if rules are met - coeffs increase with age and depriv:
    r_arr = r.reshape(5, 5)
    age_increases = (np.diff(r_arr, axis=1) >= 0).all()
    depriv_increases = (np.diff(r_arr, axis=0) <= 0).all()

    if age_increases & depriv_increases:
        if list(r) not in results:
            results.append(list(r))
            seeds_used.append(seed)

# Turn the results into a DataFrame:
df_nudged = pl.DataFrame(results, schema=coeff_names, orient='row')
df_nudged = df_nudged.insert_column(0, pl.Series('seed', seeds_used))

Check how many valid sets of coefficients there are:

In [41]:
len(df_nudged)

640

View the first few sets of coefficients:

In [42]:
df_nudged.head()

shape: (5, 26)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ seed ┆ age_less65 ┆ age_65_q00 ┆ age_70_q00 ┆ … ┆ age_65_q08 ┆ age_70_q0 ┆ age_75_q0 ┆ age_over8 │
│ ---  ┆ _q00       ┆ ---        ┆ ---        ┆   ┆ ---        ┆ 8         ┆ 8         ┆ 0_q08     │
│ i64  ┆ ---        ┆ f64        ┆ f64        ┆   ┆ f64        ┆ ---       ┆ ---       ┆ ---       │
│      ┆ f64        ┆            ┆            ┆   ┆            ┆ f64       ┆ f64       ┆ f64       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ -42  ┆ 0.0005     ┆ 0.004      ┆ 0.004      ┆ … ┆ 0.002      ┆ 0.003     ┆ 0.005     ┆ 0.01      │
│ 2    ┆ 0.0005     ┆ 0.003      ┆ 0.004      ┆ … ┆ 0.002      ┆ 0.003     ┆ 0.005     ┆ 0.01      │
│ 27   ┆ 0.0005     ┆ 0.004      ┆ 0.004      ┆ … ┆ 0.002      ┆ 0.003     ┆ 0.005     ┆ 0.01      │
│ 32   ┆ 0.0005     ┆ 0.004      ┆ 0.004      ┆ … ┆ 0.002      ┆ 0.003     ┆ 0.005     ┆ 0.01      │
│ 37   ┆ 0.0006     ┆ 0.004      ┆ 0.004      ┆ … ┆ 0.002      ┆ 0.003     ┆ 0.005     ┆ 0.01      │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

Evaluate the fitnesses:

In [43]:
df_nudged = eval_fitness_to_df(df_nudged, admissions_lists, x_lists, admissions_by_age, coeff_names, concat=True)

Only keep the sets of coefficents where the fitness is at least as good as the starting value:

In [45]:
fitness_orig = df_nudged.filter(df_nudged['seed'] == -42)['fitness'].to_numpy()[0]
mask = df_nudged['fitness'] <= fitness_orig

View these better coefficients' fitness values:

In [46]:
df_nudged.filter(mask).sort('fitness')[['seed', 'sum_sqres', 'wrong_rat', 'fitness']]

shape: (6, 4)
┌──────┬────────────┬───────────┬────────────┐
│ seed ┆ sum_sqres  ┆ wrong_rat ┆ fitness    │
│ ---  ┆ ---        ┆ ---       ┆ ---        │
│ i64  ┆ f64        ┆ f64       ┆ f64        │
╞══════╪════════════╪═══════════╪════════════╡
│ 6483 ┆ 238.324924 ┆ 1.045778  ┆ 249.234929 │
│ 9196 ┆ 239.490857 ┆ 1.050797  ┆ 251.656359 │
│ 540  ┆ 241.387779 ┆ 1.043606  ┆ 251.913656 │
│ 3575 ┆ 237.8619   ┆ 1.060951  ┆ 252.359804 │
│ 4131 ┆ 239.769863 ┆ 1.052534  ┆ 252.365853 │
│ -42  ┆ 239.191107 ┆ 1.055834  ┆ 252.546109 │
└──────┴────────────┴───────────┴────────────┘

The best set of coefficients has both a better sum of square residuals and a better age-band wrongness ratio than the starting set.

View the better sets of coefficients as a grid:

In [51]:
# Pick out original coefficients before any nudging:
coeffs_orig = df_nudged.filter(df_nudged['seed'] == -42)[coeff_names].to_numpy().flatten().reshape(5, 5)

df = df_nudged.filter(mask).sort('fitness')
for i in range(len(df)):
    # Pick out fitness score and coefficients here:
    fitness_here = df_nudged.sort('fitness')[i]['fitness'].to_numpy().flatten()[0]
    coeffs_here = df_nudged.sort('fitness')[i][coeff_names].to_numpy().flatten().reshape(5, 5)
    # Display results:
    print(f'Fitness: {fitness_here:.2f}')
    print(coeffs_here)
    print('Change from starting coefficients:')
    print(coeffs_here - coeffs_orig)
    print('\n')

Fitness: 249.23
[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.004  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[ 0.     0.     0.     0.     0.   ]
 [ 0.     0.001  0.     0.     0.   ]
 [ 0.    -0.001  0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]]


Fitness: 251.66
[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.    -0.001]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.001]
 [ 0.     0.     0.     0.     0.   ]]


Fitness: 251.91
[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.004  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.001  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[ 0.     0.     0.     0.     0.   ]
 [ 0.     0.001  0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.    -0.001  0.     0.     0.   ]]


Fitness: 252.36
[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[ 0.e+00  0.e+00  0.e+00  0.e+00  0.e+00]
 [ 0.e+00  0.e+00  0.e+00  0.e+00  0.e+00]
 [ 0.e+00  0.e+00  0.e+00  0.e+00 -1.e-03]
 [ 0.e+00  0.e+00  0.e+00  0.e+00  1.e-03]
 [ 1.e-04  0.e+00  0.e+00  0.e+00  0.e+00]]


Fitness: 252.37
[[0.0005 0.004  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[ 0.     0.     0.     0.    -0.001]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.001]
 [ 0.     0.     0.     0.     0.   ]]


Fitness: 252.55
[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]
Change from starting coefficients:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Now in principle there are combinations near the starting values that have better fitness. Check all sensible combinations of nudged coefficeints to winkle out the best one.

Note that these good combinations mostly follow a pattern: there is a pair of changed coefficients that share a row or a column, and one of the pair has increased slightly and the other decreased slightly.

### Test 3: Optimise deprivation quantiles

can we pick out a few combos that are good for each depriv quantile, then put five quantiles together to get 25 coeffs that have good overall fitness?

Grid near best combo

Take the best coefficients. For each deprivation quantile, nudge the best coefficient one or two clicks either way and calculate the new fitness scores.

In [65]:
start_coeffs = coeffs_best_deap

start_coeffs.reshape(5, 5)

array([[0.0005, 0.004 , 0.004 , 0.007 , 0.014 ],
       [0.0004, 0.003 , 0.004 , 0.007 , 0.013 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.004 , 0.005 , 0.01  ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.01  ]])

Make every combination of these start coefficients nudged up or down one or two steps:

In [71]:
def generate_new_combos_depriv(coeffs_this_depriv):
    offsets = np.array([1e-4, 1e-3, 1e-3, 1e-3, 1e-3])
    
    # Add on the offsets to make the new options:
    # Set up each value to be nudged one or two sig figs up or down.
    new_options = [
        [round(coeffs_this_depriv[j] + i*offsets[j], 4) for i in range(-2, 3)] for j in range(5)
    ]
    # Generate all combinations of these new parameters.
    # Each element of this list is a tuple of five new coeffs.
    all_new_option_combos = list(itertools.product(*new_options))
    # Only keep combinations where coefficients increase with age band:
    mask = (np.diff(all_new_option_combos, axis=1) >= 0).all(axis=1)
    all_new_option_combos = np.array(all_new_option_combos)[mask]
    return all_new_option_combos

Find every nudged variation on the best coefficients and calculate the new r-squared for that deprivation quantile.

In [72]:
new_combo_df_dict = {}

for quantile_str in quantile_str_list:
    # Set up final column names:
    depriv_ind = quantile_str_list.index(quantile_str)
    best_coeff_cols = [c for c in coeff_names if quantile_str in c]
    col_sqres = f'sum_sqres_{quantile_str}'

    # Find all nudged coefficients for this deprivation band:
    coeffs_this_depriv = start_coeffs[depriv_ind*5:depriv_ind*5+5]
    all_new_option_combos = generate_new_combos_depriv(coeffs_this_depriv)

    # Calculate fitnesses of each of the nudged sets.
    # Store results in here:
    list_sum_sqres = []
    for c, coeffs in enumerate(all_new_option_combos):
        # Population numbers for areas in this quantile:
        # Separate prediction for each deprivation quantile:
        yhat = predict_admissions(x_lists[depriv_ind], np.array(list(coeffs)))
        # Compare with the observed admissions to calculate sum of square residuals:
        sum_sqres = find_square_residuals(yhat, admissions_lists[depriv_ind])
        # Store result:
        list_sum_sqres.append(sum_sqres)

    # Place new coeff combos into dataframe:
    df_new_combos = pl.DataFrame(all_new_option_combos, schema=best_coeff_cols, orient='row')
    # Make a new column with the sum of square residuals values:
    df_new_combos = df_new_combos.with_columns(pl.Series(col_sqres, list_sum_sqres))
    
    new_combo_df_dict[quantile_str] = df_new_combos

View the results:

In [90]:
for quantile_str in list(new_combo_df_dict.keys()):
    print(quantile_str)
    # Print the best coefficients for comparison:
    cols = [c for c in coeff_names if quantile_str in c] + [f'sum_sqres_{quantile_str}', 'sum_sqres']
    print('Coeffs in best overall combo:')
    display(df_coeffs_best_deap[cols])
    # Print the nudged coeffs from best to worst:
    print('Nudged coeffs:')
    print(f'(best options out of {len(new_combo_df_dict[quantile_str])} total)')
    display(new_combo_df_dict[quantile_str].sort(f'sum_sqres_{quantile_str}').head())
    print('\n'*2)

q00
Coeffs in best overall combo:

shape: (1, 7)
┌───────────────┬────────────┬────────────┬────────────┬───────────────┬──────────────┬────────────┐
│ age_less65_q0 ┆ age_65_q00 ┆ age_70_q00 ┆ age_75_q00 ┆ age_over80_q0 ┆ sum_sqres_q0 ┆ sum_sqres  │
│ 0             ┆ ---        ┆ ---        ┆ ---        ┆ 0             ┆ 0            ┆ ---        │
│ ---           ┆ f64        ┆ f64        ┆ f64        ┆ ---           ┆ ---          ┆ f64        │
│ f64           ┆            ┆            ┆            ┆ f64           ┆ f64          ┆            │
╞═══════════════╪════════════╪════════════╪════════════╪═══════════════╪══════════════╪════════════╡
│ 0.0005        ┆ 0.004      ┆ 0.004      ┆ 0.007      ┆ 0.014         ┆ 111.087199   ┆ 239.191107 │
└───────────────┴────────────┴────────────┴────────────┴───────────────┴──────────────┴────────────┘

Nudged coeffs:
(best options out of 1750 total)

shape: (5, 6)
┌────────────────┬────────────┬────────────┬────────────┬────────────────┬───────────────┐
│ age_less65_q00 ┆ age_65_q00 ┆ age_70_q00 ┆ age_75_q00 ┆ age_over80_q00 ┆ sum_sqres_q00 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---           │
│ f64            ┆ f64        ┆ f64        ┆ f64        ┆ f64            ┆ f64           │
╞════════════════╪════════════╪════════════╪════════════╪════════════════╪═══════════════╡
│ 0.0004         ┆ 0.006      ┆ 0.006      ┆ 0.006      ┆ 0.014          ┆ 110.354891    │
│ 0.0005         ┆ 0.005      ┆ 0.005      ┆ 0.005      ┆ 0.014          ┆ 110.392239    │
│ 0.0004         ┆ 0.006      ┆ 0.006      ┆ 0.007      ┆ 0.013          ┆ 110.402224    │
│ 0.0004         ┆ 0.005      ┆ 0.006      ┆ 0.006      ┆ 0.015          ┆ 110.403983    │
│ 0.0004         ┆ 0.005      ┆ 0.005      ┆ 0.006      ┆ 0.016          ┆ 110.429618    │
└────────────────┴────────────┴────────────┴────────────┴────────────────┴───────────────┘

q02
Coeffs in best overall combo:

shape: (1, 7)
┌───────────────┬────────────┬────────────┬────────────┬───────────────┬──────────────┬────────────┐
│ age_less65_q0 ┆ age_65_q02 ┆ age_70_q02 ┆ age_75_q02 ┆ age_over80_q0 ┆ sum_sqres_q0 ┆ sum_sqres  │
│ 2             ┆ ---        ┆ ---        ┆ ---        ┆ 2             ┆ 2            ┆ ---        │
│ ---           ┆ f64        ┆ f64        ┆ f64        ┆ ---           ┆ ---          ┆ f64        │
│ f64           ┆            ┆            ┆            ┆ f64           ┆ f64          ┆            │
╞═══════════════╪════════════╪════════════╪════════════╪═══════════════╪══════════════╪════════════╡
│ 0.0004        ┆ 0.003      ┆ 0.004      ┆ 0.007      ┆ 0.013         ┆ 107.849722   ┆ 239.191107 │
└───────────────┴────────────┴────────────┴────────────┴───────────────┴──────────────┴────────────┘

Nudged coeffs:
(best options out of 2250 total)

shape: (5, 6)
┌────────────────┬────────────┬────────────┬────────────┬────────────────┬───────────────┐
│ age_less65_q02 ┆ age_65_q02 ┆ age_70_q02 ┆ age_75_q02 ┆ age_over80_q02 ┆ sum_sqres_q02 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---           │
│ f64            ┆ f64        ┆ f64        ┆ f64        ┆ f64            ┆ f64           │
╞════════════════╪════════════╪════════════╪════════════╪════════════════╪═══════════════╡
│ 0.0004         ┆ 0.003      ┆ 0.004      ┆ 0.006      ┆ 0.014          ┆ 107.800573    │
│ 0.0004         ┆ 0.004      ┆ 0.004      ┆ 0.006      ┆ 0.013          ┆ 107.823111    │
│ 0.0004         ┆ 0.003      ┆ 0.003      ┆ 0.007      ┆ 0.014          ┆ 107.823731    │
│ 0.0004         ┆ 0.003      ┆ 0.003      ┆ 0.006      ┆ 0.015          ┆ 107.840639    │
│ 0.0004         ┆ 0.003      ┆ 0.004      ┆ 0.007      ┆ 0.013          ┆ 107.849722    │
└────────────────┴────────────┴────────────┴────────────┴────────────────┴───────────────┘

q04
Coeffs in best overall combo:

shape: (1, 7)
┌───────────────┬────────────┬────────────┬────────────┬───────────────┬──────────────┬────────────┐
│ age_less65_q0 ┆ age_65_q04 ┆ age_70_q04 ┆ age_75_q04 ┆ age_over80_q0 ┆ sum_sqres_q0 ┆ sum_sqres  │
│ 4             ┆ ---        ┆ ---        ┆ ---        ┆ 4             ┆ 4            ┆ ---        │
│ ---           ┆ f64        ┆ f64        ┆ f64        ┆ ---           ┆ ---          ┆ f64        │
│ f64           ┆            ┆            ┆            ┆ f64           ┆ f64          ┆            │
╞═══════════════╪════════════╪════════════╪════════════╪═══════════════╪══════════════╪════════════╡
│ 0.0004        ┆ 0.003      ┆ 0.004      ┆ 0.006      ┆ 0.012         ┆ 108.96863    ┆ 239.191107 │
└───────────────┴────────────┴────────────┴────────────┴───────────────┴──────────────┴────────────┘

Nudged coeffs:
(best options out of 2000 total)

shape: (5, 6)
┌────────────────┬────────────┬────────────┬────────────┬────────────────┬───────────────┐
│ age_less65_q04 ┆ age_65_q04 ┆ age_70_q04 ┆ age_75_q04 ┆ age_over80_q04 ┆ sum_sqres_q04 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---           │
│ f64            ┆ f64        ┆ f64        ┆ f64        ┆ f64            ┆ f64           │
╞════════════════╪════════════╪════════════╪════════════╪════════════════╪═══════════════╡
│ 0.0003         ┆ 0.002      ┆ 0.002      ┆ 0.007      ┆ 0.014          ┆ 104.525757    │
│ 0.0003         ┆ 0.002      ┆ 0.003      ┆ 0.006      ┆ 0.014          ┆ 104.55857     │
│ 0.0003         ┆ 0.001      ┆ 0.003      ┆ 0.007      ┆ 0.014          ┆ 104.610664    │
│ 0.0003         ┆ 0.003      ┆ 0.003      ┆ 0.004      ┆ 0.014          ┆ 104.655355    │
│ 0.0003         ┆ 0.002      ┆ 0.004      ┆ 0.004      ┆ 0.014          ┆ 104.668669    │
└────────────────┴────────────┴────────────┴────────────┴────────────────┴───────────────┘

q06
Coeffs in best overall combo:

shape: (1, 7)
┌───────────────┬────────────┬────────────┬────────────┬───────────────┬──────────────┬────────────┐
│ age_less65_q0 ┆ age_65_q06 ┆ age_70_q06 ┆ age_75_q06 ┆ age_over80_q0 ┆ sum_sqres_q0 ┆ sum_sqres  │
│ 6             ┆ ---        ┆ ---        ┆ ---        ┆ 6             ┆ 6            ┆ ---        │
│ ---           ┆ f64        ┆ f64        ┆ f64        ┆ ---           ┆ ---          ┆ f64        │
│ f64           ┆            ┆            ┆            ┆ f64           ┆ f64          ┆            │
╞═══════════════╪════════════╪════════════╪════════════╪═══════════════╪══════════════╪════════════╡
│ 0.0004        ┆ 0.002      ┆ 0.004      ┆ 0.005      ┆ 0.01          ┆ 104.473782   ┆ 239.191107 │
└───────────────┴────────────┴────────────┴────────────┴───────────────┴──────────────┴────────────┘

Nudged coeffs:
(best options out of 1525 total)

shape: (5, 6)
┌────────────────┬────────────┬────────────┬────────────┬────────────────┬───────────────┐
│ age_less65_q06 ┆ age_65_q06 ┆ age_70_q06 ┆ age_75_q06 ┆ age_over80_q06 ┆ sum_sqres_q06 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---           │
│ f64            ┆ f64        ┆ f64        ┆ f64        ┆ f64            ┆ f64           │
╞════════════════╪════════════╪════════════╪════════════╪════════════════╪═══════════════╡
│ 0.0003         ┆ 0.002      ┆ 0.003      ┆ 0.006      ┆ 0.012          ┆ 102.55868     │
│ 0.0003         ┆ 0.001      ┆ 0.003      ┆ 0.007      ┆ 0.012          ┆ 102.588027    │
│ 0.0003         ┆ 0.001      ┆ 0.004      ┆ 0.006      ┆ 0.012          ┆ 102.588145    │
│ 0.0003         ┆ 0.002      ┆ 0.002      ┆ 0.007      ┆ 0.012          ┆ 102.623322    │
│ 0.0003         ┆ 0.003      ┆ 0.003      ┆ 0.005      ┆ 0.012          ┆ 102.737814    │
└────────────────┴────────────┴────────────┴────────────┴────────────────┴───────────────┘

q08
Coeffs in best overall combo:

shape: (1, 7)
┌───────────────┬────────────┬────────────┬────────────┬───────────────┬──────────────┬────────────┐
│ age_less65_q0 ┆ age_65_q08 ┆ age_70_q08 ┆ age_75_q08 ┆ age_over80_q0 ┆ sum_sqres_q0 ┆ sum_sqres  │
│ 8             ┆ ---        ┆ ---        ┆ ---        ┆ 8             ┆ 8            ┆ ---        │
│ ---           ┆ f64        ┆ f64        ┆ f64        ┆ ---           ┆ ---          ┆ f64        │
│ f64           ┆            ┆            ┆            ┆ f64           ┆ f64          ┆            │
╞═══════════════╪════════════╪════════════╪════════════╪═══════════════╪══════════════╪════════════╡
│ 0.0003        ┆ 0.002      ┆ 0.003      ┆ 0.005      ┆ 0.01          ┆ 102.232696   ┆ 239.191107 │
└───────────────┴────────────┴────────────┴────────────┴───────────────┴──────────────┴────────────┘

Nudged coeffs:
(best options out of 1450 total)

shape: (5, 6)
┌────────────────┬────────────┬────────────┬────────────┬────────────────┬───────────────┐
│ age_less65_q08 ┆ age_65_q08 ┆ age_70_q08 ┆ age_75_q08 ┆ age_over80_q08 ┆ sum_sqres_q08 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---           │
│ f64            ┆ f64        ┆ f64        ┆ f64        ┆ f64            ┆ f64           │
╞════════════════╪════════════╪════════════╪════════════╪════════════════╪═══════════════╡
│ 0.0001         ┆ 0.003      ┆ 0.004      ┆ 0.004      ┆ 0.012          ┆ 98.631977     │
│ 0.0002         ┆ 0.001      ┆ 0.004      ┆ 0.005      ┆ 0.012          ┆ 98.692418     │
│ 0.0002         ┆ 0.002      ┆ 0.003      ┆ 0.005      ┆ 0.012          ┆ 98.702951     │
│ 0.0001         ┆ 0.002      ┆ 0.003      ┆ 0.007      ┆ 0.012          ┆ 98.709033     │
│ 0.0001         ┆ 0.003      ┆ 0.003      ┆ 0.006      ┆ 0.012          ┆ 98.709283     │
└────────────────┴────────────┴────────────┴────────────┴────────────────┴───────────────┘

For all deprivation quantiles, the sets of nudged coeffs contain an option with lower sum of square residuals than the one in the best overall combo.

Gather the coefficients that are best for each deprviation quantile:

In [81]:
best_combos = []
best_combo_cols = []

for q, quantile_str in enumerate(list(new_combo_df_dict.keys())):
    df = new_combo_df_dict[quantile_str].sort(f'sum_sqres_{quantile_str}')
    df = df[0] if q < 4 else df[3]
    cols = [c for c in df.columns if c.startswith('age')]
    best_combo_cols += cols
    best_combos += list(df[cols].to_numpy().flatten())

Check that the complete set of coefficients meet the requirements of increasing with age and deprivation:

In [88]:
print(np.array(best_combos).reshape(5, 5))

print('\nCheck coeffs increase with age band (across):')
print(np.diff(np.array(best_combos).reshape(5, 5), axis=1) >= 0)

print('\nCheck coeffs increase with deprivation (downwards):')
print(np.diff(np.array(best_combos).reshape(5, 5), axis=0) <= 0)

[[0.0004 0.006  0.006  0.006  0.014 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0003 0.002  0.002  0.007  0.014 ]
 [0.0003 0.002  0.003  0.006  0.012 ]
 [0.0001 0.002  0.003  0.007  0.012 ]]

Check coeffs increase with age band (across):
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

Check coeffs increase with deprivation (downwards):
[[ True  True  True  True  True]
 [ True  True  True False  True]
 [ True  True False  True  True]
 [ True  True  True False  True]]

These requirements are not met! The values break the pattern in a handful of places.

Instead pick more carefully to ensure these conditions are met.

It doesn't work!

Instead, try a few combinations of "best" results. For each deprivation quantile in turn, use its best results and then select results for the other quantiles that work around it.

The following functions search an array of coefficients to find sets that work with a given set of coefficients. They find either coefficients that always increase or stay the same as the reference set, or that always decrease or stay the same.

In [91]:
def pick_conditions_met(combo, all_combos, pick_more=True):
    """
    Find options where all coeffs are more than/same as fixed values.

    Inputs
    ------
    combo      - list. Fixed coefficients.
    all_combos - np.array. One row per set of coefficients.
                 Assume sorted from best to worst r-squared.
    Returns
    -------
    list. The selected coefficients from the big list.
    """
    # List of masks, one mask per age band.
    # Masks are for whether the coeffs for this age band
    # are more or equal to the fixed value for this age band.
    if pick_more:
        masks = [(all_combos[:, p] >= combo[p]) for p in range(len(combo))]
    else:
        masks = [(all_combos[:, p] <= combo[p]) for p in range(len(combo))]
    # Gather masks:
    masks = np.vstack(masks).T
    # Check where condition is met for all age bands:
    valid_mask = masks.all(axis=1)
    # Select this index "pick", the first in the list where the
    # condition is met for all age bands.
    pick = np.where(valid_mask == True)[0][0]
    # Return a list of the coefficients in this row of the table:
    return all_combos[pick]

Pick out combos:

In [98]:
def pick_combos(fixed_combo, new_combo_100_df_dict, q):
    """
    Pick combos of all good coeffs that meet rules.

    Fix the coefficients for the qth quantile in the list.
    Then pick coefficients for the adjacent quantiles that meet rules
    and continue until all quantiles have been picked.
    Picked coefficients must increase with age band and with level
    of deprivation.

    Inputs
    ------
    fixed_combo           - list. Five coefficients that are fixed.
    new_combo_100_df_dict - dict. One entry per deprivation quantile.
                            Each entry is a dataframe of coefficients
                            and their r-squared value.
    q                     - int. Index of depriv quantile for the
                            fixed combo.

    Returns
    -------
    best_combo - list. Length 25, picked coefficients.
    """
    def gather_coeff_combos(p):
        """
        Change big dataframe of coeff combos to array for picking.
        """
        # Find the name of the r-squared column for the next combo:
        p_str = list(new_combo_100_df_dict.keys())[p]
        # Pick out the coefficients and r-squared for this combo:
        arr = new_combo_100_df_dict[p_str].sort(f'sum_sqres_{p_str}').to_numpy()
        # Cut off r-squared column:
        arr = arr[:, :-1]
        return arr
        
    # Set up coeff storage.
    # Store the coeffs for each quantile in their own list in order
    # in the following list of lists. Start with empty lists...
    best_combo = [[]] * 5
    # ... fill in one list of coeffs...
    best_combo[q] = list(fixed_combo)
    # ... then use that filled list to select the adjacent lists.
    for p in range(q+1, 5):
        # Find the combos where values should be less than or same as the
        # starting values.
        arr = gather_coeff_combos(p)
        # Find the best coeff combo that meets the decreasing criteria:
        picked_coeffs = pick_conditions_met(best_combo[p-1], arr, pick_more=False)
        # Store result:
        best_combo[p] = list(picked_coeffs)
    for p in range(q-1, -1, -1):
        # Find the combos where values should be more than or same as the
        # starting values.
        arr = gather_coeff_combos(p)
        # Find the best coeff combo that meets the increasing criteria:
        picked_coeffs = pick_conditions_met(best_combo[p+1], arr)
        # Store result:
        best_combo[p] = list(picked_coeffs)
    # Return a single flat list of coeffs, length 25.
    best_combo = sum(best_combo, [])
    return best_combo

Run this function for each quantile in turn. For each loop, a different quantile's coefficients are fixed first. Then the other quantiles' coefficients have to work around those fixed values.

In [99]:
best_picked_combos = {}
# Each item will be a list of 25 coeffs.

for q, quantile_str in enumerate(list(new_combo_df_dict.keys())):
    # Pick out a list of five coefficients for this depriv quantile:
    fixed_combo = (new_combo_df_dict[quantile_str]
                   .sort(f'sum_sqres_{quantile_str}')[0]
                   .to_numpy().flatten()[:-1])
    # Pick out coeffs for the other quantiles that work well with this:
    best_picked_combos[quantile_str] = pick_combos(
        fixed_combo, new_combo_df_dict, q)

Calculate their sum of square residuals:

In [103]:
best_picked_combos_r2s = {}

for quantile_str, best_combo in best_picked_combos.items():
    # Calculate fitnesses of each of the nudged sets.
    sum_sqres, sum_sqres_by_depriv = many_sum_sqres(best_combo, x_lists, admissions_lists)
    best_picked_combos_r2s[quantile_str] = sum_sqres_by_depriv + [sum_sqres]

Rearrange the picked coefficients into dataframes:

In [104]:
best_picked_combos_dfs = {}
age_label_list = ['less65', '65-70', '70-75', '75-80', 'over80']

for quantile_str, best_combo in best_picked_combos.items():
    # Make a dataframe:
    data = np.array(best_combo).reshape(5, 5)
    # Add deprivation column:
    data = np.hstack((np.array(quantile_str_list).reshape(5, 1), data))
    df = pl.DataFrame(data, schema=['depriv_quantile_min'] + age_label_list)
    for col in age_label_list:
        df = df.with_columns(pl.col(col).cast(float))
    # Place r-squared results in the dataframe:
    list_sum_sqres = best_picked_combos_r2s[quantile_str]
    df = df.with_columns(pl.Series('sum_sqres', list_sum_sqres[:-1]))
    
    best_picked_combos_dfs[quantile_str] = df

View the results:

In [105]:
for quantile_str, df in best_picked_combos_dfs.items():
    print(f'First fixed: {quantile_str}')
    print(f'Overall sum sqres: {best_picked_combos_r2s[quantile_str][-1]:.5f}')
    display(df)
    print('')

First fixed: q00
Overall sum sqres: 234.50419

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.006 ┆ 0.006 ┆ 0.006 ┆ 0.014  ┆ 110.354891 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.004 ┆ 0.006 ┆ 0.014  ┆ 107.800573 │
│ q04                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.014  ┆ 104.55857  │
│ q06                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.012  ┆ 102.55868  │
│ q08                 ┆ 0.0002 ┆ 0.002 ┆ 0.003 ┆ 0.005 ┆ 0.012  ┆ 98.702951  │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

First fixed: q02
Overall sum sqres: 234.50419

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.006 ┆ 0.006 ┆ 0.006 ┆ 0.014  ┆ 110.354891 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.004 ┆ 0.006 ┆ 0.014  ┆ 107.800573 │
│ q04                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.014  ┆ 104.55857  │
│ q06                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.012  ┆ 102.55868  │
│ q08                 ┆ 0.0002 ┆ 0.002 ┆ 0.003 ┆ 0.005 ┆ 0.012  ┆ 98.702951  │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

First fixed: q04
Overall sum sqres: 234.63866

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.005 ┆ 0.005 ┆ 0.007 ┆ 0.015  ┆ 110.442113 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.003 ┆ 0.007 ┆ 0.014  ┆ 107.823731 │
│ q04                 ┆ 0.0003 ┆ 0.002 ┆ 0.002 ┆ 0.007 ┆ 0.014  ┆ 104.525757 │
│ q06                 ┆ 0.0003 ┆ 0.002 ┆ 0.002 ┆ 0.007 ┆ 0.012  ┆ 102.623322 │
│ q08                 ┆ 0.0002 ┆ 0.002 ┆ 0.002 ┆ 0.007 ┆ 0.012  ┆ 98.86709   │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

First fixed: q06
Overall sum sqres: 234.50419

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.006 ┆ 0.006 ┆ 0.006 ┆ 0.014  ┆ 110.354891 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.004 ┆ 0.006 ┆ 0.014  ┆ 107.800573 │
│ q04                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.014  ┆ 104.55857  │
│ q06                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.012  ┆ 102.55868  │
│ q08                 ┆ 0.0002 ┆ 0.002 ┆ 0.003 ┆ 0.005 ┆ 0.012  ┆ 98.702951  │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

First fixed: q08
Overall sum sqres: 234.73615

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.006 ┆ 0.006 ┆ 0.006 ┆ 0.014  ┆ 110.354891 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.004 ┆ 0.006 ┆ 0.014  ┆ 107.800573 │
│ q04                 ┆ 0.0002 ┆ 0.003 ┆ 0.004 ┆ 0.005 ┆ 0.014  ┆ 104.839407 │
│ q06                 ┆ 0.0002 ┆ 0.003 ┆ 0.004 ┆ 0.005 ┆ 0.012  ┆ 102.870443 │
│ q08                 ┆ 0.0001 ┆ 0.003 ┆ 0.004 ┆ 0.004 ┆ 0.012  ┆ 98.631977  │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

Compare the overall r-squared scores for the five options:

In [107]:
pl.DataFrame(
    np.vstack((
        quantile_str_list,
        [round(best_picked_combos_r2s[quantile_str][-1], 3) for quantile_str in quantile_str_list]
    )).T,
    schema=['fixed_depriv_quantile_min', 'sum_sqres']
)

shape: (5, 2)
┌───────────────────────────┬───────────┐
│ fixed_depriv_quantile_min ┆ sum_sqres │
│ ---                       ┆ ---       │
│ str                       ┆ str       │
╞═══════════════════════════╪═══════════╡
│ q00                       ┆ 234.504   │
│ q02                       ┆ 234.504   │
│ q04                       ┆ 234.639   │
│ q06                       ┆ 234.504   │
│ q08                       ┆ 234.736   │
└───────────────────────────┴───────────┘

The lowest overall sum of square residuals is for the sets of coefficients that first fixed the 0.0-0.2, 0.2-0.4 and 0.6-0.8 deprivation quantiles.

Compare results with SSNAP-derived coefficients

Recalculate total fitness:

In [109]:
best_picked_combos_dfs['q00']

shape: (5, 7)
┌─────────────────────┬────────┬───────┬───────┬───────┬────────┬────────────┐
│ depriv_quantile_min ┆ less65 ┆ 65-70 ┆ 70-75 ┆ 75-80 ┆ over80 ┆ sum_sqres  │
│ ---                 ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---        │
│ str                 ┆ f64    ┆ f64   ┆ f64   ┆ f64   ┆ f64    ┆ f64        │
╞═════════════════════╪════════╪═══════╪═══════╪═══════╪════════╪════════════╡
│ q00                 ┆ 0.0004 ┆ 0.006 ┆ 0.006 ┆ 0.006 ┆ 0.014  ┆ 110.354891 │
│ q02                 ┆ 0.0004 ┆ 0.003 ┆ 0.004 ┆ 0.006 ┆ 0.014  ┆ 107.800573 │
│ q04                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.014  ┆ 104.55857  │
│ q06                 ┆ 0.0003 ┆ 0.002 ┆ 0.003 ┆ 0.006 ┆ 0.012  ┆ 102.55868  │
│ q08                 ┆ 0.0002 ┆ 0.002 ┆ 0.003 ┆ 0.005 ┆ 0.012  ┆ 98.702951  │
└─────────────────────┴────────┴───────┴───────┴───────┴────────┴────────────┘

In [110]:
sum_sqres, rat, fitness, ratios_by_age, sum_sqres_by_depriv = eval_admissions(
    best_picked_combos['q00'],
    admissions_lists,
    x_lists,
    admissions_by_age
)

# Best R^2 from all genetic algorithm results:
fitness_best = df_best_gens['fitness'].min()
sum_sqres_best = df_best_gens['sum_sqres'].min()

print(f'New sum_sqres: {sum_sqres:.4f}')
print(f'Old sum_sqres: {sum_sqres_best:.4f}')

print(f'New fitness: {fitness:.4f}')
print(f'Old fitness: {fitness_best:.4f}')

New sum_sqres: 234.5042
Old sum_sqres: 237.4549
New fitness: 338.3078
Old fitness: 252.5461

Sum of square residuals has improved using these nudged coefficients, but fitness is much worse.

So it doesn't look likely that we'll find a good fit by looking at deprivation band alone.

### Test 4: Optimise age bands

can we pick out a few combos that are good for each age band, then put five sets together to get 25 coeffs that have good overall fitness?

The randomly-picked best fits seem to improve the "wrongness" ratio in the age bands much more than the overall sum of square residuals. So find ways to nudge the coefficients that result in better fits to the total national admissions for each age band.

In [111]:
dict_offsets_for_ages = {  # np.array([1e-4, 1e-3, 1e-3, 1e-3, 1e-3])
    'less65': 1e-4,
    '65': 1e-3,
    '70': 1e-3,
    '75': 1e-3,
    'over80': 1e-3,
}

All combos of offsets for ages:

In [112]:
combo_scales_for_ages = np.array([c for c in itertools.product([-2, -1, 0, 1, 2], repeat=5)])

In [113]:
len(combo_scales_for_ages)

3125

For a set of coeffs, apply these offsets and then recalculate fitness:

In [114]:
def wrong_rat(x_lists_here, coeffs, admissions_by_age):
    # Predictions for each age band across England:
    # Separate prediction for each deprivation quantile:
    # coeffs = individual[(i*5):(i*5)+5] #* np.array(coeffs_ssnap)
    yhat_list = (
        [(x_lists_here[i] * coeffs[i]).sum() for i in range(len(coeffs))]
    )
    predictions_by_age = sum(yhat_list)
    # Divide the admissions by age band by the observed values:
    predictions_by_age /= admissions_by_age_here
    return predictions_by_age

In [115]:
age_bands = ['less65', '65', '70', '75', 'over80']

dict_nudged_dfs = {}
for a, age_band in enumerate(age_bands):
    x_lists_here = [x_lists[i][a] for i in range(5)]  # only data for this age band
    admissions_by_age_here = admissions_by_age[a]
    
    age_cols = [c for c in df_best_gens.columns if f'_{age_band}_' in c]
    age_offset = dict_offsets_for_ages[age_band]
    combo_offsets_for_age = combo_scales_for_ages * age_offset
    
    start_coeffs = df_best_gens.sort('fitness')[0][age_cols].to_numpy().flatten()
    
    # df_nudge_here = pl.DataFrame(schema=age_cols + ['rat'])
    df_nudge_here = pl.DataFrame()
    # rats = []#[] for i in range(5)]
    
    for c, combo in enumerate(combo_offsets_for_age):
        coeffs_here = start_coeffs + np.array(combo)
        # Check that coeffs increase with deprivation:
        if all(np.diff(coeffs_here) <= 0.0) & all(coeffs_here > 0.0):
            rat = wrong_rat(x_lists_here, coeffs_here, admissions_by_age_here)
            abs_rat = abs(1.0 - rat)
            # rats.append(round(rat, 7))
            row = dict(zip(age_cols + ['rat', 'abs_rat'], list(coeffs_here) + [round(rat, 7), round(abs_rat, 7)]))
            # if c == 0:
            #     df_nudge_here = pl.DataFrame(row)
            # else:
            df_nudge_here = pl.concat((df_nudge_here, pl.DataFrame(row)))
        else:
            # Don't calculate results for here.
            pass
    # Store result:
    dict_nudged_dfs[age_band] = df_nudge_here

In [116]:
coeffs_ssnap

array([0.000408, 0.002644, 0.003735, 0.006005, 0.011558])

In [117]:
coeffs_ssnap_round = [0.0004, 0.003, 0.004, 0.006, 0.012]

In [118]:
i = 0
for key, df in dict_nudged_dfs.items():
    print(key)
    display(df.filter(df[f'age_{key}_q04'] == coeffs_ssnap_round[i]).sort('abs_rat')[:10])
    i += 1

less65

shape: (10, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────────┬───────────┐
│ age_less65_q ┆ age_less65_q ┆ age_less65_q ┆ age_less65_q ┆ age_less65_q ┆ rat       ┆ abs_rat   │
│ 00           ┆ 02           ┆ 04           ┆ 06           ┆ 08           ┆ ---       ┆ ---       │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ f64       ┆ f64       │
│ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆           ┆           │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════════╪═══════════╡
│ 0.0006       ┆ 0.0006       ┆ 0.0004       ┆ 0.0002       ┆ 0.0002       ┆ 0.9996408 ┆ 0.0003592 │
│ 0.0006       ┆ 0.0006       ┆ 0.0004       ┆ 0.0003       ┆ 0.0001       ┆ 0.999514  ┆ 0.000486  │
│ 0.0007       ┆ 0.0005       ┆ 0.0004       ┆ 0.0003       ┆ 0.0001       ┆ 1.0012324 ┆ 0.0012324 │
│ 0.0007       ┆ 0.0005       ┆ 0.0004       ┆ 0.0002       ┆ 0.0002       ┆ 1.0013592 ┆ 0.0013592 │
│ 0.0007       ┆ 0.0004       ┆ 0.0004       ┆ 0.0003       ┆ 0.0002       ┆ 0.9955844 ┆ 0.0044156 │
│ 0.0007       ┆ 0.0004       ┆ 0.0004       ┆ 0.0004       ┆ 0.0001       ┆ 0.9954576 ┆ 0.0045424 │
│ 0.0006       ┆ 0.0005       ┆ 0.0004       ┆ 0.0003       ┆ 0.0002       ┆ 0.993866  ┆ 0.006134  │
│ 0.0006       ┆ 0.0005       ┆ 0.0004       ┆ 0.0004       ┆ 0.0001       ┆ 0.9937392 ┆ 0.0062608 │
│ 0.0007       ┆ 0.0006       ┆ 0.0004       ┆ 0.0002       ┆ 0.0001       ┆ 1.0070071 ┆ 0.0070071 │
│ 0.0006       ┆ 0.0004       ┆ 0.0004       ┆ 0.0003       ┆ 0.0003       ┆ 0.9882181 ┆ 0.0117819 │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────────┴───────────┘

65

shape: (10, 7)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ age_65_q00 ┆ age_65_q02 ┆ age_65_q04 ┆ age_65_q06 ┆ age_65_q08 ┆ rat       ┆ abs_rat   │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 0.005      ┆ 0.003      ┆ 0.003      ┆ 0.002      ┆ 0.001      ┆ 0.9978634 ┆ 0.0021366 │
│ 0.004      ┆ 0.004      ┆ 0.003      ┆ 0.002      ┆ 0.001      ┆ 1.0051216 ┆ 0.0051216 │
│ 0.005      ┆ 0.004      ┆ 0.003      ┆ 0.001      ┆ 0.001      ┆ 0.9833508 ┆ 0.0166492 │
│ 0.004      ┆ 0.003      ┆ 0.003      ┆ 0.002      ┆ 0.002      ┆ 1.01735   ┆ 0.01735   │
│ 0.004      ┆ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.001      ┆ 1.0196342 ┆ 0.0196342 │
│ 0.006      ┆ 0.003      ┆ 0.003      ┆ 0.001      ┆ 0.001      ┆ 0.9760925 ┆ 0.0239075 │
│ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.002      ┆ 1.0391208 ┆ 0.0391208 │
│ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.001      ┆ 0.9581258 ┆ 0.0418742 │
│ 0.003      ┆ 0.003      ┆ 0.003      ┆ 0.002      ┆ 0.002      ┆ 0.9558416 ┆ 0.0441584 │
│ 0.006      ┆ 0.004      ┆ 0.003      ┆ 0.001      ┆ 0.001      ┆ 1.0448592 ┆ 0.0448592 │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

70

shape: (10, 7)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ age_70_q00 ┆ age_70_q02 ┆ age_70_q04 ┆ age_70_q06 ┆ age_70_q08 ┆ rat       ┆ abs_rat   │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 0.006      ┆ 0.006      ┆ 0.004      ┆ 0.003      ┆ 0.001      ┆ 0.9991764 ┆ 0.0008236 │
│ 0.006      ┆ 0.006      ┆ 0.004      ┆ 0.002      ┆ 0.002      ┆ 0.9988826 ┆ 0.0011174 │
│ 0.005      ┆ 0.004      ┆ 0.004      ┆ 0.004      ┆ 0.002      ┆ 0.9903172 ┆ 0.0096828 │
│ 0.005      ┆ 0.004      ┆ 0.004      ┆ 0.003      ┆ 0.003      ┆ 0.9900235 ┆ 0.0099765 │
│ 0.004      ┆ 0.004      ┆ 0.004      ┆ 0.004      ┆ 0.003      ┆ 1.0132933 ┆ 0.0132933 │
│ 0.006      ┆ 0.005      ┆ 0.004      ┆ 0.003      ┆ 0.002      ┆ 1.0142795 ┆ 0.0142795 │
│ 0.006      ┆ 0.005      ┆ 0.004      ┆ 0.004      ┆ 0.001      ┆ 1.0145733 ┆ 0.0145733 │
│ 0.005      ┆ 0.005      ┆ 0.004      ┆ 0.004      ┆ 0.001      ┆ 0.9752141 ┆ 0.0247859 │
│ 0.005      ┆ 0.005      ┆ 0.004      ┆ 0.003      ┆ 0.002      ┆ 0.9749203 ┆ 0.0250797 │
│ 0.006      ┆ 0.004      ┆ 0.004      ┆ 0.003      ┆ 0.003      ┆ 1.0293827 ┆ 0.0293827 │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

75

shape: (10, 7)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ age_75_q00 ┆ age_75_q02 ┆ age_75_q04 ┆ age_75_q06 ┆ age_75_q08 ┆ rat       ┆ abs_rat   │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 0.007      ┆ 0.007      ┆ 0.006      ┆ 0.005      ┆ 0.005      ┆ 0.9995902 ┆ 0.0004098 │
│ 0.007      ┆ 0.007      ┆ 0.006      ┆ 0.006      ┆ 0.004      ┆ 0.9992987 ┆ 0.0007013 │
│ 0.009      ┆ 0.008      ┆ 0.006      ┆ 0.004      ┆ 0.004      ┆ 0.9970786 ┆ 0.0029214 │
│ 0.009      ┆ 0.008      ┆ 0.006      ┆ 0.005      ┆ 0.003      ┆ 0.9967871 ┆ 0.0032129 │
│ 0.008      ┆ 0.006      ┆ 0.006      ┆ 0.005      ┆ 0.005      ┆ 0.9941362 ┆ 0.0058638 │
│ 0.008      ┆ 0.006      ┆ 0.006      ┆ 0.006      ┆ 0.004      ┆ 0.9938447 ┆ 0.0061553 │
│ 0.009      ┆ 0.007      ┆ 0.006      ┆ 0.006      ┆ 0.003      ┆ 1.0072999 ┆ 0.0072999 │
│ 0.009      ┆ 0.007      ┆ 0.006      ┆ 0.005      ┆ 0.004      ┆ 1.0075914 ┆ 0.0075914 │
│ 0.007      ┆ 0.006      ┆ 0.006      ┆ 0.006      ┆ 0.005      ┆ 1.010103  ┆ 0.010103  │
│ 0.008      ┆ 0.008      ┆ 0.006      ┆ 0.006      ┆ 0.003      ┆ 1.0127539 ┆ 0.0127539 │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

over80

shape: (10, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────────┬───────────┐
│ age_over80_q ┆ age_over80_q ┆ age_over80_q ┆ age_over80_q ┆ age_over80_q ┆ rat       ┆ abs_rat   │
│ 00           ┆ 02           ┆ 04           ┆ 06           ┆ 08           ┆ ---       ┆ ---       │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ f64       ┆ f64       │
│ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆           ┆           │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════════╪═══════════╡
│ 0.015        ┆ 0.014        ┆ 0.012        ┆ 0.011        ┆ 0.008        ┆ 1.0000637 ┆ 0.0000637 │
│ 0.014        ┆ 0.012        ┆ 0.012        ┆ 0.011        ┆ 0.01         ┆ 0.9995308 ┆ 0.0004692 │
│ 0.015        ┆ 0.014        ┆ 0.012        ┆ 0.01         ┆ 0.009        ┆ 1.0009259 ┆ 0.0009259 │
│ 0.014        ┆ 0.012        ┆ 0.012        ┆ 0.012        ┆ 0.009        ┆ 0.9986685 ┆ 0.0013315 │
│ 0.013        ┆ 0.013        ┆ 0.012        ┆ 0.012        ┆ 0.009        ┆ 1.0013433 ┆ 0.0013433 │
│ 0.016        ┆ 0.013        ┆ 0.012        ┆ 0.01         ┆ 0.009        ┆ 0.9982512 ┆ 0.0017488 │
│ 0.013        ┆ 0.013        ┆ 0.012        ┆ 0.011        ┆ 0.01         ┆ 1.0022055 ┆ 0.0022055 │
│ 0.016        ┆ 0.012        ┆ 0.012        ┆ 0.012        ┆ 0.008        ┆ 1.0024256 ┆ 0.0024256 │
│ 0.016        ┆ 0.013        ┆ 0.012        ┆ 0.011        ┆ 0.008        ┆ 0.9973889 ┆ 0.0026111 │
│ 0.016        ┆ 0.012        ┆ 0.012        ┆ 0.011        ┆ 0.009        ┆ 1.0032879 ┆ 0.0032879 │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────────┴───────────┘

In [119]:
i = 0
dict_nudged_dfs_ssnapq04 = {}
for key, df in dict_nudged_dfs.items():
    dict_nudged_dfs_ssnapq04[key] = df.filter(df[f'age_{key}_q04'] == coeffs_ssnap_round[i]).sort('abs_rat')
    i += 1


gather combos that are pretty good, check for increasing coeffs, calculate r-squared. Try various combos depending on resulting total r-squared by depriv quantile, e.g. if best coeffs all weighted heavily in one quantile and the answer is too high, then pick that quantile first to change to another set of coeffs.

..

Check all combos of the top 6 options. Picked because it runs a decent amount (7776 combos) but doesn't take forever to run.

In [120]:
# Every combo of the top ten indices:
index_combos = [c for c in itertools.product(range(6), repeat=5)]

In [121]:
fitness_keys = [
    'sum_sqres',
    'wrong_rat',
    'fitness',
    'wrong_rat_under65',
    'wrong_rat_65',
    'wrong_rat_70',
    'wrong_rat_75',
    'wrong_rat_over80',
    'sum_sqres_q00',
    'sum_sqres_q02',
    'sum_sqres_q04',
    'sum_sqres_q06',
    'sum_sqres_q08',
]

df_index_combos = pl.DataFrame()

for i, index_combo in enumerate(index_combos):
    print(f'{i+1:4d} out of {len(index_combos)}', end='\r')
    
    dict_inds = {
        'less65': index_combo[0],
        '65': index_combo[1],
        '70': index_combo[2],
        '75': index_combo[3],
        'over80': index_combo[4]
    }
    
    # Gather coeffs for these inds:
    all_coeff_cols = []
    all_coeffs = []
    for age_band, df in dict_nudged_dfs_ssnapq04.items():
        # 'less65', '65', '70', '75', 'over80'
        # Pick out the coeffs for this age band:
        coeff_cols_here = [c for c in df.columns if c.startswith('age')]
        all_coeff_cols += coeff_cols_here
        all_coeffs += list(df[dict_inds[age_band]][coeff_cols_here].to_numpy().flatten())
    # Order coeffs as usual:
    df_coeffs = pl.DataFrame(np.array(all_coeffs).reshape(1, len(all_coeffs)), schema=all_coeff_cols)
    df_coeffs = df_coeffs[coeff_names]
    coeffs = df_coeffs.to_numpy().flatten().reshape(5, 5)
    # print(coeffs)
    # print('\n')

    # Check that coeffs increase with deprivation:
    if np.all(np.diff(coeffs, axis=1) >= 0.0):
        # Calculate fitness:
        sum_sqres, rat, fitness, ratios_by_age, sum_sqres_by_depriv = eval_admissions(
            coeffs.flatten(),
            admissions_lists,
            x_lists,
            admissions_by_age
        )
        # Gather values for results:
        results_values = np.concatenate((coeffs.flatten(), [sum_sqres, rat, fitness], ratios_by_age, sum_sqres_by_depriv))
        df_coeffs = pl.DataFrame(results_values.reshape(1, len(results_values)), schema=coeff_names + fitness_keys)
        # Store result:
        df_index_combos = pl.concat((df_index_combos, df_coeffs))
    else:
        # Don't bother with coeffs that don't increase with deprivation.
        pass

In [122]:
df_index_combos.sort('fitness')

shape: (6_264, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 108.96863 ┆ 103.86957 ┆ 115.3215 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆ 8         ┆ 6        │
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 103.86957 ┆ 107.9011 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 8         ┆ 61       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 116.18871 ┆ 108.96863 ┆ 109.20789 ┆ 107.9011 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 1         ┆ 61       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 113.86687 ┆ 108.96863 ┆ 109.20789 ┆ 107.9011 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆ 1         ┆ 61       │
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 109.20789 ┆ 107.9011 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 1         ┆ 61       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.0007    ┆ 0.006     ┆ 0.006     ┆ 0.009     ┆ … ┆ 132.57029 ┆ 108.96863 ┆ 120.39071 ┆ 197.2892 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 1         ┆ 41       │
│ 0.0007    ┆ 0.005     ┆ 0.006     ┆ 0.009     ┆ … ┆ 141.34991 ┆ 108.96863 ┆ 113.98455 ┆ 208.9820 │
│           ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆ 5         ┆ 28       │
│ 0.0006    ┆ 0.005     ┆ 0.006     ┆ 0.009     ┆ … ┆ 159.37407 ┆ 108.96863 ┆ 113.98455 ┆ 208.9820 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 5         ┆ 28       │
│ 0.0006    ┆ 0.006     ┆ 0.006     ┆ 0.009     ┆ … ┆ 149.27940 ┆ 108.96863 ┆ 113.98455 ┆ 208.9820 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆ 5         ┆ 28       │
│ 0.0007    ┆ 0.006     ┆ 0.006     ┆ 0.009     ┆ … ┆ 132.57029 ┆ 108.96863 ┆ 113.98455 ┆ 208.9820 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 5         ┆ 28       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Best fitnesses worse than the start value!

In [123]:
df_index_combos.sort('fitness')[0][coeff_names].to_numpy().reshape(5, 5)

array([[0.0007, 0.004 , 0.004 , 0.007 , 0.014 ],
       [0.0004, 0.004 , 0.004 , 0.007 , 0.012 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.012 ],
       [0.0003, 0.002 , 0.004 , 0.005 , 0.011 ],
       [0.0002, 0.001 , 0.003 , 0.005 , 0.01  ]])

In [124]:
coeffs_ssnap

array([0.000408, 0.002644, 0.003735, 0.006005, 0.011558])

In [125]:
df_best_gens.sort('fitness')[0]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 22.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 74         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Pair-wise nudging

walk around the starting coeffs.

Try all pairs of nudges in each row and column. Pick the one that has best effect on fitness. Then find best pair to match whatever has already changed. Keep iterating until no more improvements can be made.

Set up pair indices.

In [126]:
row_col_inds = [c for c in itertools.product(range(5), repeat=2)]

row_col_inds

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [127]:
def build_nudge_df(start_coeffs, first_pass=False):
    """
    """
    def convert_to_dataframe(coeffs_here, nudged_cols):
        """
        """
        # Convert to dataframe:
        data_here = coeffs_here.flatten()
        df_here = pl.DataFrame(np.array(data_here).reshape(1, len(data_here)), schema=nudged_cols)
        return df_here
    
    nudged_cols = coeff_names
    
    df_nudges = pl.DataFrame()
    
    # coeffs_here = np.array([s for s in start_coeffs]).reshape(5, 5)
    # # Store result:
    # df_here = convert_to_dataframe(coeffs_here, nudged_cols)
    # df_nudges = pl.concat((df_nudges, df_here))
    if first_pass:
        # Force two coeffs to change.
          m_pairs_available = [(1.0, -1.0), (-1.0, 1.0)]
    else:
        # Only one coeff has to change, but two are allowed to.
        m_pairs_available = [(1.0, -1.0), (-1.0, 1.0), (1.0, 0.0), (0.0, 1.0), (-1.0, 0.0), (0.0, -1.0)]
    
    for r, (row_a, col_a) in enumerate(row_col_inds[:3]):
        step_a = 1e-4 if col_a == 0 else 1e-3
        # Compare with each other point in the same row:
        for col_b in range(5):
            if col_b != col_a:
                step_b = 1e-4 if col_b == 0 else 1e-3
                for m_pairs in m_pairs_available:
                    # Nudge coefficients:
                    coeffs_here = np.array([s for s in start_coeffs]).reshape(5, 5)
                    coeffs_here[row_a, col_a] += m_pairs[0]*step_a
                    coeffs_here[row_a, col_b] += m_pairs[1]*step_b
                    # Store result:
                    df_here = convert_to_dataframe(coeffs_here, nudged_cols)
                    df_nudges = pl.concat((df_nudges, df_here))
        for row_b in range(5):
            if row_b != row_a:
                # Same step size.
                for m_pairs in m_pairs_available:
                    # Nudge coefficients:
                    coeffs_here = np.array([s for s in start_coeffs]).reshape(5, 5)
                    coeffs_here[row_a, col_a] += m_pairs[0]*step_a
                    coeffs_here[row_b, col_a] += m_pairs[1]*step_a
        
                    # Store result:
                    df_here = convert_to_dataframe(coeffs_here, nudged_cols)
                    df_nudges = pl.concat((df_nudges, df_here))
    # Remove repeats
    # (from comparing A then B and also B then A):
    df_nudges = df_nudges.unique()
    return df_nudges

In [128]:
def find_nudged_fitnesses(df_nudges):
    df_nudges_fitness = pl.DataFrame()
    
    fitness_keys = [
        'sum_sqres',
        'wrong_rat',
        'fitness',
        'wrong_rat_under65',
        'wrong_rat_65',
        'wrong_rat_70',
        'wrong_rat_75',
        'wrong_rat_over80',
        'sum_sqres_q00',
        'sum_sqres_q02',
        'sum_sqres_q04',
        'sum_sqres_q06',
        'sum_sqres_q08',
    ]
    for i in range(len(df_nudges)):
        coeffs = df_nudges[i][coeff_names].to_numpy().flatten()
        
        if np.all(np.diff(coeffs.reshape(5, 5), axis=1) >= 0.0) & np.all(np.diff(coeffs.reshape(5, 5), axis=0) <= 0.0):
            sum_sqres, rat, fitness, ratios_by_age, sum_sqres_by_depriv = eval_admissions(
                coeffs,
                admissions_lists,
                x_lists,
                admissions_by_age
            )
        else:        
            # Overwrite results if coeffs invalid:
            sum_sqres = np.nan
            rat = np.nan
            fitness = np.nan
            ratios_by_age = [np.nan] * 5
            sum_sqres_by_depriv = [np.nan] * 5
    
        # Gather values for results:
        results_values = np.concatenate((coeffs.flatten(), [sum_sqres, rat, fitness], ratios_by_age, sum_sqres_by_depriv))
        df_coeffs = pl.DataFrame(results_values.reshape(1, len(results_values)), schema=coeff_names + fitness_keys)
        # Store result:
        df_nudges_fitness = pl.concat((df_nudges_fitness, df_coeffs))
    return df_nudges_fitness

In [129]:
dict_nudged_results = {}

for d in df_best_gens['dir']:
    
    start_coeffs = df_best_gens.filter(df_best_gens['dir'] == d)[coeff_names].to_numpy().flatten()
    df_nudge_history = find_nudged_fitnesses(pl.DataFrame(start_coeffs.reshape(1, len(start_coeffs)), schema=coeff_names))
    
    keep_going_please = True
    k = 0
    while keep_going_please:
        first_pass = False if k > 0 else True
        df_nudges = build_nudge_df(start_coeffs, first_pass)
        df_nudges = find_nudged_fitnesses(df_nudges)
        # Pick out the best one:
        df_nudges = df_nudges.sort('fitness')[0]  # CONSIDER not doing fitness, separate r2 or wrong rat depending on whether row or col changed?
        start_coeffs = df_nudges[coeff_names].to_numpy().flatten()
        df_nudge_history = pl.concat((df_nudge_history, df_nudges))
        k += 1
        if (k > 2) & (len(df_nudge_history) != len(df_nudge_history.unique())):
            keep_going_please = False
        elif k > 100:
            keep_going_please = False
            print('Cutting off after 100 iterations.')

    # Store results:
    dict_nudged_results[d] = df_nudge_history

In [130]:
df_best_nudged = pl.DataFrame()

for d, df in dict_nudged_results.items():
    df_best_nudged = pl.concat((df_best_nudged, df.filter(df['fitness'] == df['fitness'].min())[0]))

In [131]:
with pl.Config(set_tbl_rows=100):
    display(df_best_nudged.sort('fitness'))

shape: (100, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 47       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 74       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 7         ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 47       │
│ 0.0004    ┆ 0.004     ┆ 0.007     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.26677 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 9         ┆ 2         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.01      ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 64       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 105.11410 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │

In [132]:
df_best_nudged.sort('fitness')[0][coeff_names].to_numpy().flatten().reshape(5, 5)

array([[0.0005, 0.005 , 0.005 , 0.007 , 0.013 ],
       [0.0004, 0.003 , 0.004 , 0.007 , 0.013 ],
       [0.0004, 0.002 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.003 , 0.005 , 0.011 ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.01  ]])

In [133]:
pl.concat((df_best_nudged.mean(), df_best_nudged.std(), 100.0*df_best_nudged.std() / df_best_nudged.mean()))

shape: (3, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.000479  ┆ 0.00474   ┆ 0.00477   ┆ 0.00735   ┆ … ┆ 108.15261 ┆ 106.61694 ┆ 105.66078 ┆ 102.2308 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 3         ┆ 8         ┆ 66       │
│ 0.000048  ┆ 0.000441  ┆ 0.000489  ┆ 0.000575  ┆ … ┆ 0.581558  ┆ 0.829024  ┆ 1.723623  ┆ 0.356809 │
│ 9.972522  ┆ 9.300506  ┆ 10.259585 ┆ 7.825295  ┆ … ┆ 0.53772   ┆ 0.777573  ┆ 1.63128   ┆ 0.349022 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [134]:
with pl.Config(set_tbl_rows=12):
    for d, df in dict_nudged_results.items():
        display(df_best_gens.filter(df_best_gens['dir'] == d))
        display(df)
        print(df_best_gens.filter(df_best_gens['dir'] == d)[coeff_names].to_numpy().flatten().reshape(5, 5))
        print('')
        print(df.filter(df['fitness'] == df['fitness'].min())[0][coeff_names].to_numpy().flatten().reshape(5, 5))
        print('\n'*2)

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 33.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 105.83841 ┆ 102.23269 │
│ 00         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 5         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 105.83841 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 105.83841 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 102.97085 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 102.97085 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 105.12324 ┆ 102.97085 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 102.97085 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 5         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 5         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0003 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 33.0  ┆ 0.0004     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 01         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0004    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0004 0.003  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 43.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 02         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.92941 ┆ 105.63901 │
│ 03         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 2         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.92941 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 12       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.92941 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 12       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 12       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 12       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 74       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.61612 ┆ 106.67578 ┆ 104.92941 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆ 4         ┆ 3         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.92941 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 3         ┆ 74       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.004  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0004 0.002  0.003  0.004  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 39.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.23269 │
│ 04         ┆       ┆            ┆            ┆   ┆           ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 19.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 05         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.016 ]
 [0.0004 0.004  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 23.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 06         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0005 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.016 ]
 [0.0004 0.004  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 07         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 36.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47791 ┆ 102.23269 │
│ 08         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47378 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 46.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 106.95302 ┆ 102.04766 │
│ 09         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 5         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (13, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 106.95302 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.90881 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 9         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 9         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 9         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0003 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 10         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.82946 ┆ 107.72117 ┆ 102.23269 │
│ 11         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (11, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.82946 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.006     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.82946 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.006     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.82946 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.006     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.82946 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.003  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.016 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 25.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.04766 │
│ 12         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 3         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 27.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 13         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 21.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.23269 │
│ 14         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 15         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 16         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 20.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.23269 │
│ 17         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 18         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 34.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.23269 │
│ 19         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 21.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.04766 │
│ 20         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0004    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 64       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.001  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 21         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 21.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.23269 │
│ 22         ┆       ┆            ┆            ┆   ┆           ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 30.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.04766 │
│ 23         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 23.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.23269 │
│ 24         ┆       ┆            ┆            ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (4, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 21.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 25         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 20.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 107.72117 ┆ 102.23269 │
│ 26         ┆       ┆            ┆            ┆   ┆ 3         ┆ 1         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.015 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 39.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.86803 ┆ 107.72117 ┆ 102.04766 │
│ 27         ┆       ┆            ┆            ┆   ┆           ┆ 5         ┆ 7         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.86803 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.86803 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.009     ┆ … ┆ 108.40745 ┆ 106.86803 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.01      ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.01      ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.01      ┆ … ┆ 108.40745 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.01   0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 19.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 28         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 24.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.92356 ┆ 102.23269 │
│ 29         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 1         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 42.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.72117 ┆ 102.23269 │
│ 30         ┆       ┆            ┆            ┆   ┆ 7         ┆ 1         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 47.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.07976 ┆ 102.23269 │
│ 31         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.07976 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 34.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.36882 ┆ 106.75011 ┆ 103.90582 ┆ 102.23269 │
│ 32         ┆       ┆            ┆            ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 4         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0005 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.92356 ┆ 102.23269 │
│ 33         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 1         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 33.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.04766 │
│ 34         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 31.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 106.95302 ┆ 102.23269 │
│ 35         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 5         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 106.95302 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.006     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.007     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.30198 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 8         ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.007     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.30198 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 8         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.007     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.26677 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 9         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.007     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.26677 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 9         ┆ 2         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.007     ┆ 0.008     ┆ … ┆ 108.49105 ┆ 106.26677 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 9         ┆ 2         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.007     ┆ 0.008     ┆ … ┆ 110.93268 ┆ 106.26677 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 9         ┆ 2         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.004  0.007  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 36         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 33.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.23269 │
│ 37         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 31.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 38         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.23269 │
│ 39         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 70.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 105.68817 ┆ 99.88842  │
│ 40         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 105.68817 ┆ 99.88842 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆          │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.47236 ┆ 99.88842 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 6         ┆          │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.47236 ┆ 99.88842 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 6         ┆          │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 104.54565 ┆ 99.88842 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 5         ┆          │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.47236 ┆ 99.88842 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 6         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.011 ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.011 ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 35.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 41         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 27.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 42         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 20.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.04766 │
│ 43         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 40.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 44         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 105.63901 │
│ 45         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 2         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 12       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 12       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 12       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 12       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 105.6390 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 12       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 74       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.009  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.004  0.01  ]]

[[0.0004 0.005  0.005  0.009  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.004  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 15.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.58867 │
│ 46         ┆       ┆            ┆            ┆   ┆ 5         ┆           ┆ 7         ┆ 4         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 74       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.5886 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 74       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.004  0.01  ]]

[[0.0004 0.005  0.005  0.009  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.004  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 27.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.04766 │
│ 47         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 19.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 48         ┆       ┆            ┆            ┆   ┆ 5         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.016 ]
 [0.0004 0.004  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 35.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 104.47791 ┆ 102.04766 │
│ 49         ┆       ┆            ┆            ┆   ┆ 3         ┆ 1         ┆ 3         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 104.47791 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 104.47378 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.015 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 38.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 50         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 35.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90582 ┆ 102.23269 │
│ 51         ┆       ┆            ┆            ┆   ┆ 2         ┆ 5         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.47236 ┆ 102.23269 │
│ 52         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 6         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 6         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 5         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0003 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 53         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 24.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.72103 ┆ 102.23269 │
│ 54         ┆       ┆            ┆            ┆   ┆           ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.016 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 42.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 55         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 30.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 56         ┆       ┆            ┆            ┆   ┆ 5         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 56.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 57         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (4, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 27.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.23269 │
│ 58         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 43.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 59         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.05400 ┆ 106.86803 ┆ 107.72117 ┆ 102.23269 │
│ 60         ┆       ┆            ┆            ┆   ┆ 5         ┆ 5         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 2         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 2         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 2         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 2         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 2         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.016 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 43.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 103.92356 ┆ 102.23269 │
│ 61         ┆       ┆            ┆            ┆   ┆ 5         ┆           ┆ 1         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 103.92356 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 1         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 36.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.99864 ┆ 102.23269 │
│ 62         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.99864 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.99864 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 105.11410 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 105.11410 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.006     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 105.11410 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 105.11410 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.014 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0006 0.004  0.004  0.007  0.014 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0003 0.003  0.004  0.006  0.012 ]
 [0.0003 0.002  0.004  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 30.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 106.95302 ┆ 102.23269 │
│ 63         ┆       ┆            ┆            ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 106.95302 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.009     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 8         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0004 0.003  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0006 0.004  0.004  0.008  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0003 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90582 ┆ 102.23269 │
│ 64         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 19.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 65         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 111.25068 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.008  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 17.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.47236 ┆ 102.04766 │
│ 66         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 6         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.47236 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 6         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.47236 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 6         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.47236 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 6         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 6         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.54565 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 5         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.47236 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 6         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 23.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 67         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 68         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.04766 │
│ 69         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 70         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 67.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 71         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.04766 │
│ 72         ┆       ┆            ┆            ┆   ┆           ┆ 1         ┆ 7         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 7         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.008  0.016 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 48.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.23269 │
│ 73         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 22.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 74         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.23269 │
│ 75         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 34.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 107.72117 ┆ 102.23269 │
│ 76         ┆       ┆            ┆            ┆   ┆ 2         ┆ 5         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.86803 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.84972 ┆ 106.05894 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 2         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.005  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 27.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.75111 ┆ 102.23269 │
│ 77         ┆       ┆            ┆            ┆   ┆ 7         ┆ 1         ┆ 9         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.67578 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 4         ┆ 9         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.008  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 30.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 78         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.008  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 22.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 79         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.36882 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.93181 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0005 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.016 ]
 [0.0004 0.004  0.004  0.007  0.012 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 39.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 80         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 26.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47791 ┆ 102.23269 │
│ 81         ┆       ┆            ┆            ┆   ┆ 5         ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (4, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47791 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.05400 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.012 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 21.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.04766 │
│ 82         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 2         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 25.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 83         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 29.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 104.72103 ┆ 102.04766 │
│ 84         ┆       ┆            ┆            ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 104.72103 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.75011 ┆ 104.72103 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 64       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 104.72103 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.61612 ┆ 106.75011 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆ 1         ┆ 7         ┆ 64       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.6492 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 64       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.016 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.001  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 16.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 85         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 39.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90881 ┆ 108.20430 │
│ 86         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 8         ┆ 9         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90881 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 8         ┆ 09       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90881 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 8         ┆ 09       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90881 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 8         ┆ 09       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90881 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 8         ┆ 47       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 2         ┆ 47       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 47       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 47       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.61612 ┆ 106.67578 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆ 4         ┆ 2         ┆ 47       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 103.90582 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 2         ┆ 47       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.009 ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0004 0.002  0.003  0.005  0.009 ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 11.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.04766 │
│ 87         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 7         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 44.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.23269 │
│ 88         ┆       ┆            ┆            ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (9, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.75011 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 1         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.67578 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 4         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 25.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.23269 │
│ 89         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (11, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 107.82311 ┆ 106.27626 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.008  0.014 ]
 [0.0004 0.004  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 90         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90881 ┆ 102.23269 │
│ 91         ┆       ┆            ┆            ┆   ┆ 7         ┆           ┆ 8         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 8         ┆ 96       │
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 7         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 111.25068 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 7         ┆ 8         ┆ 96       │
│ 0.0007    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 7         ┆ 8         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0006 0.004  0.004  0.007  0.013 ]
 [0.0005 0.003  0.004  0.007  0.013 ]
 [0.0003 0.003  0.004  0.006  0.012 ]
 [0.0003 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 25.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 103.47236 ┆ 108.20430 │
│ 92         ┆       ┆            ┆            ┆   ┆ 3         ┆ 1         ┆ 6         ┆ 9         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 103.47236 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 6         ┆ 09       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.006     ┆ … ┆ 107.80057 ┆ 106.75011 ┆ 103.47236 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆ 6         ┆ 09       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 09       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 108.2043 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 09       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 47       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 47       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 107.80057 ┆ 106.67578 ┆ 103.47236 ┆ 103.9355 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 4         ┆ 6         ┆ 47       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0003 0.002  0.003  0.005  0.009 ]]

[[0.0004 0.005  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.006  0.014 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.011 ]
 [0.0004 0.002  0.003  0.005  0.009 ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 23.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.23269 │
│ 93         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 8         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (10, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.90881 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 108.96863 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 103.86957 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 8         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 105.12324 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 9         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 9         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 9         ┆ 96       │
│ 0.0006    ┆ 0.005     ┆ 0.005     ┆ 0.008     ┆ … ┆ 109.65222 ┆ 106.03801 ┆ 107.75111 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 9         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.008  0.013 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0003 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 18.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.23269 │
│ 94         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 103.90582 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.004  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.013 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.011 ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 35.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 104.92941 ┆ 102.23269 │
│ 95         ┆       ┆            ┆            ┆   ┆           ┆           ┆ 3         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (6, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.006     ┆ … ┆ 109.65222 ┆ 108.96863 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 109.65222 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.27626 ┆ 104.92941 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 3         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.014 ]
 [0.0005 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 28.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.92941 ┆ 102.04766 │
│ 96         ┆       ┆            ┆            ┆   ┆           ┆ 1         ┆ 3         ┆ 8         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.009     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.008     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.75011 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 3         ┆ 68       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.006     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
│ 0.0004    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 108.40745 ┆ 106.67578 ┆ 104.92941 ┆ 102.0476 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 3         ┆ 68       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.009  0.014 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.003  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

[[0.0004 0.005  0.005  0.007  0.016 ]
 [0.0004 0.003  0.004  0.006  0.013 ]
 [0.0004 0.002  0.004  0.006  0.011 ]
 [0.0004 0.002  0.003  0.006  0.01  ]
 [0.0004 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 46.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 97         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.005  0.007  0.015 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 14.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.23269 │
│ 98         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.003     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.72103 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
│ 0.0005    ┆ 0.005     ┆ 0.005     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 106.27626 ┆ 107.72117 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 6         ┆ 7         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.003  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.005  0.005  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.002  0.004  0.006  0.012 ]
 [0.0004 0.002  0.003  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 19.0  ┆ 0.0005     ┆ 0.003      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.66531 ┆ 102.23269 │
│ 99         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (7, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.66531 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.003     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.66531 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 108.34504 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0006    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 108.34504 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 3         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

[[0.0005 0.003  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0003 0.003  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

[[0.0005 0.004  0.004  0.007  0.014 ]
 [0.0004 0.003  0.004  0.007  0.013 ]
 [0.0004 0.003  0.004  0.006  0.012 ]
 [0.0004 0.002  0.004  0.005  0.01  ]
 [0.0003 0.002  0.003  0.005  0.01  ]]

In [135]:
df_best_gens.sort('fitness')[0][coeff_names].to_numpy().flatten().reshape(5, 5)

array([[0.0005, 0.004 , 0.004 , 0.007 , 0.014 ],
       [0.0004, 0.003 , 0.004 , 0.007 , 0.013 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.004 , 0.005 , 0.01  ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.01  ]])

In [136]:
df_nudge_history.sort('fitness')[0][coeff_names].to_numpy().flatten().reshape(5, 5)

array([[0.0005, 0.004 , 0.004 , 0.007 , 0.014 ],
       [0.0004, 0.003 , 0.004 , 0.007 , 0.013 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.004 , 0.005 , 0.01  ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.01  ]])

In [137]:
df_best_gens.sort('fitness')[0]

shape: (1, 40)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ dir        ┆ # gen ┆ age_less65 ┆ age_65_q00 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres │
│ ---        ┆ ---   ┆ _q00       ┆ ---        ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ _q08      │
│ str        ┆ f64   ┆ ---        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆ f64        ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ randomseed ┆ 22.0  ┆ 0.0005     ┆ 0.004      ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.23269 │
│ 74         ┆       ┆            ┆            ┆   ┆ 2         ┆           ┆ 2         ┆ 6         │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [138]:
start_coeffs.reshape(5, 5)

array([[0.0005, 0.004 , 0.004 , 0.007 , 0.014 ],
       [0.0004, 0.003 , 0.004 , 0.007 , 0.013 ],
       [0.0004, 0.003 , 0.004 , 0.006 , 0.012 ],
       [0.0004, 0.002 , 0.004 , 0.005 , 0.01  ],
       [0.0003, 0.002 , 0.003 , 0.005 , 0.01  ]])

In [139]:
df_nudges#.unique()

shape: (1, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ … ┆ sum_sqres ┆ sum_sqres ┆ sum_sqres ┆ sum_sqre │
│ 5_q00     ┆ 0         ┆ 0         ┆ 0         ┆   ┆ _q02      ┆ _q04      ┆ _q06      ┆ s_q08    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0005    ┆ 0.004     ┆ 0.004     ┆ 0.007     ┆ … ┆ 107.84972 ┆ 108.96863 ┆ 104.47378 ┆ 102.2326 │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆ 2         ┆ 96       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘